Libraries used
```{r}

setwd("C:/Users/lavil/source/repos/LukVill/MATH-M148")

library(tidyverse)
library(lubridate)
library(hms)

```

Run this code for random 1000 rows sample
```{r}

luke_export_dir <- 'C:/Users/lavil/source/repos/LukVill/Misc Data/export.csv'

# this is based off of Luke's directory!!! #
export_head <- read_csv(luke_export_dir, n_max = 1000)

```

Run this code if the WHOLE data needs to be imported
```{r}

luke_export_dir <- "C:/Users/lavil/source/repos/LukVill/Misc Data/export.csv"

# this is based off of Luke's directory!!! #
export <- read_csv(luke_export_dir)

```

Event Definitions Load
```{r}

event_def <- read_csv("Event Definitions.csv")

```


Questions to Answer

```{r}

# 1. 
nrow(export)

# 2.
num_cust <- export %>% select(customer_id) %>% n_distinct()

# 3.
# return customers are customers who have at least 2 interactions total on different days
# mutate month, day, year, time into export
export <- export %>% mutate(months = month(event_timestamp), days = day(event_timestamp), years = year(event_timestamp), times = as_hms(event_timestamp))
# group by id and dates to get each interaction per date and count (table of all interactions per date per customer)
# group by id to get days of interaction per customer, filter those more than 1
num_return_cust <- export %>% group_by(customer_id,months,days,years) %>% count() %>% ungroup() %>% group_by(customer_id) %>% count() %>% filter(n > 1)

# 4.
num_acct_custs <- export %>% group_by(account_id) %>% count() %>% filter(n > 1) %>% select(account_id) %>% n_distinct()
num_cust_accts <- export %>% group_by(customer_id) %>% count() %>% filter(n > 1) %>% select(customer_id) %>% n_distinct()

# 5.
beg_date <- export[which.min(export$event_timestamp),]
end_date <- export[which.max(export$event_timestamp),]

# 6.

#export_head$journey_steps_until_end
#export_head %>% slice(1:24)
export %>% filter(customer_id == -784961211)
# 24 with export_head
# 45 with export, two different acct id for same customer
# for each unique customer/acct pair, journey id describes # of interactions for that pair

# 7. 
# na detection: no na's
# date mutation

```

Initial Personal Analysis
```{r}

mode_stats <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

glimpse(export)


# DEFINE COLUMNS IN EXPORT
# journey_steps
unique_seq <- export %>% select(journey_steps_until_end) %>% unique() %>% pull(1)
unique_seq <- sort(unique_seq)
length(unique_seq)
unique_seq[3299]
# it seems the seq is 1-3299 are there missing numbers?
idx <- any((1:3299) != unique_seq)
idx
# no missing numbers. 
# CONCLUSION: min = 1, max = 3299

# try to see pattern after conjoining event_def with export
glimpse(event_def)
event_def %>% filter(str_detect(event_name, "web"))
# each event has an id. in export, event_name and ed_id are correlated.

# gets count of unique ed_id
export_head %>% select(ed_id) %>% ggplot(aes(x = ed_id)) + geom_bar()

# mode of ed_id
export %>% pull(ed_id) %>% mode_stats()

# 19 is most frequent ed_id

# filter

export %>% filter(ed_id == 19)

# there is significance in ed_id,
# also there is significance in the event name and account number
# event name is what the person does on the website
# account number is the user???
help("replace_na")
```

ed_id analysis


event_name analysis
```{r}

event_def

# what is milestone number?


```
